# Generated by Django 5.2.3 on 2025-08-07 13:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Versão do nome amigável para URLs, ex: 'dicas-sustentaveis'",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
            },
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CLIENTE", "Cliente"),
                            ("VENDEDOR", "Vendedor"),
                            ("ONG", "ONG"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "nome_negocio",
                    models.CharField(
                        blank=True,
                        help_text="O nome comercial do vendedor ou da ONG.",
                        max_length=255,
                        verbose_name="Nome da Loja/Negócio",
                    ),
                ),
                ("telefone", models.CharField(max_length=15)),
                ("endereco", models.TextField()),
                (
                    "cnpj",
                    models.CharField(
                        blank=True,
                        help_text="Obrigatório para Vendedores e ONGs",
                        max_length=18,
                        null=True,
                        unique=True,
                        verbose_name="CNPJ",
                    ),
                ),
                (
                    "descricao_parceiro",
                    models.TextField(
                        blank=True,
                        help_text="Uma breve descrição sobre o parceiro",
                        verbose_name="Descrição da Empresa/ONG",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "quantidade_estoque",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Quantidade total que o vendedor tem disponível.",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="O vendedor pode desmarcar para 'pausar' o anúncio do produto.",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="produtos",
                        to="core.categoria",
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        limit_choices_to={"tipo": "VENDEDOR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produtos",
                        to="core.perfil",
                    ),
                ),
            ],
        ),
    ]
