# Generated by Django 5.2.4 on 2025-08-05 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('telefone', models.CharField(max_length=15)),
                ('endereco', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AdminSistema',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.usuario')),
                ('permissao_geral', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Administrador do Sistema',
                'verbose_name_plural': 'Administradores do Sistema',
            },
            bases=('core.usuario',),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.usuario')),
                ('restricao_alimenticia', models.CharField(blank=True, max_length=255, null=True)),
                ('realizar_pedido', models.CharField(blank=True, max_length=255, null=True)),
                ('solicitar_devolucao', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
            bases=('core.usuario',),
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.usuario')),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('cadastrar_produtos', models.BooleanField(default=False)),
                ('editar_informacoes', models.BooleanField(default=False)),
                ('realizar_doacao', models.BooleanField(default=False)),
                ('cadastrar_estoque', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
            bases=('core.usuario',),
        ),
    ]
