# Generated by Django 5.2.4 on 2025-08-06 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tipo', models.CharField(choices=[('CLIENTE', 'Cliente'), ('FORNECEDOR', 'Fornecedor'), ('ONG', 'ONG')], max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('endereco', models.TextField()),
                ('cnpj', models.CharField(blank=True, help_text='Obrigatório para Fornecedores e ONGs', max_length=18, null=True, unique=True, verbose_name='CNPJ')),
                ('descricao_parceiro', models.TextField(blank=True, help_text='Uma breve descrição sobre o parceiro', verbose_name='Descrição da Empresa/ONG')),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='usuario_ptr',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='usuario_ptr',
        ),
        migrations.DeleteModel(
            name='AdminSistema',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Fornecedor',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
