# Generated by Django 5.2.3 on 2025-10-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacotesurpresa',
            name='data_disponibilidade_fim',
            field=models.DateField(blank=True, help_text='Data até a qual o pacote estará disponível.', null=True),
        ),
        migrations.AddField(
            model_name='pacotesurpresa',
            name='data_disponibilidade_inicio',
            field=models.DateField(blank=True, help_text='Data a partir da qual o pacote estará disponível.', null=True),
        ),
        migrations.AddField(
            model_name='pacotesurpresa',
            name='instrucoes_especiais',
            field=models.TextField(blank=True, help_text="Instruções para o cliente sobre o pacote (ex: 'consumir em 2 dias')."),
        ),
        migrations.AddField(
            model_name='pacotesurpresa',
            name='produtos_possiveis',
            field=models.ManyToManyField(blank=True, help_text='Produtos que podem compor este pacote surpresa (para controle interno, não visível ao cliente).', to='core.produto'),
        ),
        migrations.AddField(
            model_name='pacotesurpresa',
            name='tipo_conteudo',
            field=models.CharField(blank=True, help_text="Ex: 'Frutas e Vegetais', 'Produtos de Padaria', 'Itens de Mercearia'", max_length=100),
        ),
    ]
