# Generated by Django 5.2.3 on 2025-10-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='valor_produtos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
