# Generated by Django 5.2.3 on 2025-08-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='email',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='nome',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('VENDEDOR', 'Vendedor'), ('ONG', 'ONG')], max_length=20),
        ),
    ]
