# Generated by Django 5.2.3 on 2025-08-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código que o cliente irá usar (ex: PROMO10)', max_length=50, unique=True)),
                ('tipo_desconto', models.CharField(choices=[('PERCENTUAL', '% Percentual'), ('VALOR_FIXO', 'R$ Valor Fixo')], default='PERCENTUAL', max_length=20)),
                ('valor_desconto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_validade', models.DateField(blank=True, help_text='O cupom não será válido após esta data. Deixe em branco para não expirar.', null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('usos_realizados', models.PositiveIntegerField(default=0, editable=False)),
                ('limite_uso', models.PositiveIntegerField(default=1, help_text='Quantas vezes este cupom pode ser usado no total.')),
                ('valor_minimo_compra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
