# Generated by Django 5.2.3 on 2026-01-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cnpj',
            field=models.CharField(blank=True, default=None, help_text='Obrigatório para Vendedores e ONGs.', max_length=18, null=True, unique=True, verbose_name='CNPJ'),
        ),
    ]
