# Generated by Django 5.2.3 on 2025-11-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo_quantidade',
            field=models.CharField(blank=True, choices=[('PESA', 'Kg'), ('MEDE', 'Litros'), ('QUANTIA', 'Unidade')], null=True),
        ),
    ]
