# Generated by Django 5.2.3 on 2026-01-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cep',
            field=models.CharField(help_text='CEP no formato 00000-000', max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cnpj',
            field=models.CharField(default='', help_text='Obrigatório para Vendedores e ONGs.', max_length=18, verbose_name='CNPJ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='descricao_parceiro',
            field=models.TextField(help_text='Uma breve descrição sobre o parceiro.', verbose_name='Descrição da Empresa/ONG'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='estado',
            field=models.CharField(help_text='Sigla do estado, ex: SP', max_length=2),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='imagem_carrossel1',
            field=models.ImageField(default='', upload_to='carrossel/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='imagem_carrossel2',
            field=models.ImageField(default='', upload_to='carrossel/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='imagem_carrossel3',
            field=models.ImageField(default='', upload_to='carrossel/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nome_completo',
            field=models.CharField(help_text='Nome completo do cliente.', max_length=255, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nome_negocio',
            field=models.CharField(help_text='O nome comercial do vendedor ou da ONG.', max_length=255, verbose_name='Nome da Loja/ONG'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='objetivo',
            field=models.TextField(verbose_name='Objetivos da ONG'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(blank=True, help_text='Telefone com DDD, ex: (11) 99999-9999', max_length=20),
        ),
    ]
