# Generated by Django 5.2.3 on 2026-01-23 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacotesurpresa',
            name='vendedor',
            field=models.ForeignKey(limit_choices_to={'tipo': 'VENDEDOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='pacote', to='core.perfil'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo_quantidade',
            field=models.CharField(blank=True, choices=[('PESA', 'Kg'), ('MEDE', 'Litros'), ('QUANTIA', 'Unidade')], max_length=50, null=True),
        ),
    ]
