# Generated by Django 5.2.3 on 2025-08-07 13:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "data_pedido",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("endereco_entrega", models.CharField(max_length=255)),
                (
                    "forma_pagamento",
                    models.CharField(
                        choices=[
                            ("CARTAO_CREDITO", "Cartão de Crédito"),
                            ("PIX", "Pix"),
                            ("CARTAO_DEBITO", "Cartão de Débito"),
                        ],
                        default="PIX",
                        max_length=20,
                    ),
                ),
                (
                    "status_pagamento",
                    models.CharField(
                        choices=[
                            ("AGUARDANDO", "Aguardando Pagamento"),
                            ("PAGO", "Pago"),
                            ("FALHA", "Falha no Pagamento"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="AGUARDANDO",
                        max_length=20,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        limit_choices_to={"tipo": "CLIENTE"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos",
                        to="core.perfil",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PedidoVendedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AGUARDANDO", "Aguardando Aprovação"),
                            ("EM_PREPARO", "Em Preparo"),
                            ("A_CAMINHO", "A Caminho"),
                            ("ENTREGUE", "Entregue"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="AGUARDANDO",
                        max_length=20,
                    ),
                ),
                (
                    "valor_subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor total dos itens deste vendedor.",
                        max_digits=10,
                    ),
                ),
                (
                    "pedido_principal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_pedidos",
                        to="core.pedido",
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        limit_choices_to={"tipo": "VENDEDOR"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos_recebidos",
                        to="core.perfil",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Quantidade de unidades do produto neste item.",
                    ),
                ),
                (
                    "preco_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Preço do produto no momento em que o pedido foi feito.",
                        max_digits=10,
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_pedidos",
                        to="core.produto",
                    ),
                ),
                (
                    "sub_pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="core.pedidovendedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do Pedido",
                "verbose_name_plural": "Itens dos Pedidos",
                "unique_together": {("sub_pedido", "produto")},
            },
        ),
    ]
