# Generated by Django 5.2.3 on 2025-10-14 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pacotesurpresa_data_disponibilidade_fim_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itempedido',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='pacote_surpresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedidos', to='core.pacotesurpresa'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedidos', to='core.produto'),
        ),
    ]
