# Generated by Django 5.2.3 on 2025-08-06 22:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_perfil_email_remove_perfil_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text="Versão do nome amigável para URLs, ex: 'dicas-sustentaveis'", max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_estoque', models.PositiveIntegerField(default=0, help_text='Quantidade total que o vendedor tem disponível.')),
                ('ativo', models.BooleanField(default=True, help_text="O vendedor pode desmarcar para 'pausar' o anúncio do produto.")),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='core.categoria')),
                ('vendedor', models.ForeignKey(limit_choices_to={'tipo': 'VENDEDOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='core.perfil')),
            ],
        ),
    ]
