# Generated by Django 5.2.3 on 2025-08-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cupom'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaleConosco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mensagem', models.TextField(help_text='conteudo da mensagem')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NOVA', 'Nova'), ('RESPONDIDA', 'Respondida'), ('FECHADA', 'Fechada')], default='NOVA', max_length=10)),
            ],
        ),
    ]
