# Generated by Django 5.2.3 on 2026-02-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_perfil_cnpj_alter_receita_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cnpj',
            field=models.CharField(blank=True, default=None, help_text='Obrigatório para Vendedores e ONGs.', max_length=18, null=True, unique=True, verbose_name='CNPJ'),
        ),
    ]
