# Generated by Django 5.2.3 on 2025-08-07 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_pedido_pedidovendedor_itempedido"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField(help_text="Descrição dos itens doados")),
                ("quantidade_doada", models.PositiveIntegerField()),
                ("data_doacao", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AGUARDANDO", "Aguardando Retirada"),
                            ("CONCLUIDA", "Concluída"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="AGUARDANDO",
                        max_length=20,
                    ),
                ),
                (
                    "doador",
                    models.ForeignKey(
                        help_text="Fornecedor que está doando",
                        limit_choices_to={"tipo": "FORNECEDOR"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="doacoes_feitas",
                        to="core.perfil",
                    ),
                ),
                (
                    "ong",
                    models.ForeignKey(
                        limit_choices_to={"tipo": "ONG"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="doacoes_recebidas",
                        to="core.perfil",
                    ),
                ),
            ],
        ),
    ]
