# Generated by Django 5.2.3 on 2025-09-29 21:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notificacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('codigo_produto', models.CharField(max_length=20, unique=True)),
                ('data_fabricacao', models.DateField(blank=True, null=True)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('quantidade_estoque', models.PositiveIntegerField(default=0)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='avaliacao',
            options={},
        ),
        migrations.RenameField(
            model_name='avaliacao',
            old_name='data',
            new_name='data_avaliacao',
        ),
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='titulo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='nota',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 Estrela'), (2, '2 Estrelas'), (3, '3 Estrelas'), (4, '4 Estrelas'), (5, '5 Estrelas')]),
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='lojas/')),
                ('localizacao', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loja', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EstatisticaVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_vendas', models.PositiveIntegerField(default=0)),
                ('receita_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('loja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas', to='core.loja')),
            ],
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='receita',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='texto',
        ),
        migrations.CreateModel(
            name='ReceitaAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveIntegerField(help_text='Nota de 1 a 5 estrelas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('texto', models.TextField(blank=True, help_text='Escreva um comentário sobre a receita (opcional)', verbose_name='Comentário')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_feitas', to=settings.AUTH_USER_MODEL)),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='core.receita')),
            ],
            options={
                'ordering': ['-data'],
                'unique_together': {('receita', 'autor')},
            },
        ),
    ]
