# Generated by Django 5.2.3 on 2025-09-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cadastro_produto_produtos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produtos',
        ),
        migrations.AddField(
            model_name='produtovendedor',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
