# Generated by Django 5.2.3 on 2025-08-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_categoria_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='nome_negocio',
            field=models.CharField(blank=True, help_text='O nome comercial do vendedor ou da ONG.', max_length=255, verbose_name='Nome da Loja/Negócio'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cnpj',
            field=models.CharField(blank=True, help_text='Obrigatório para Vendedores e ONGs', max_length=18, null=True, unique=True, verbose_name='CNPJ'),
        ),
    ]
