# Generated by Django 5.2.3 on 2025-08-07 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_doacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doacao",
            name="doador",
            field=models.ForeignKey(
                help_text="Vendedor que está doando",
                limit_choices_to={"tipo": "VENDEDOR"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="doacoes_feitas",
                to="core.perfil",
            ),
        ),
    ]
