# Generated by Django 5.2.3 on 2025-11-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_carrinho_itemcarrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tipo_quantidade',
            field=models.CharField(blank=True, choices=[('PESA', 'Kg'), ('MEDE', 'Lt'), ('QUANTIA', 'Unidade')], null=True),
        ),
    ]
