# Generated by Django 5.2.3 on 2025-08-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_doacao_doador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itempedido",
            name="preco_unitario",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Preço do produto no momento da compra. Preenchido automaticamente se deixado em branco.",
                max_digits=10,
                null=True,
            ),
        ),
    ]
