# Generated by Django 5.2.3 on 2025-08-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_categoriareceita_receita_ingrediente_etapapreparo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='logo_ong',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
