# Generated by Django 5.2.3 on 2025-08-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_perfil_logo_ong'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem de apresentação do produto', null=True, upload_to='produtos/'),
        ),
    ]
