# Generated by Django 5.2.3 on 2025-08-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='imagem_carrossel1',
            field=models.ImageField(blank=True, help_text='Apenas para ONGs', null=True, upload_to='carrossel/'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='imagem_carrossel2',
            field=models.ImageField(blank=True, help_text='Apenas para ONGs', null=True, upload_to='carrossel/'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='imagem_carrossel3',
            field=models.ImageField(blank=True, help_text='Apenas para ONGs', null=True, upload_to='carrossel/'),
        ),
    ]
