# Generated by Django 5.2.3 on 2025-08-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo_produto',
            field=models.CharField(blank=True, help_text='Código de barras ou SKU. Deve ser único.', max_length=50, null=True, unique=True, verbose_name='Código do Produto (SKU)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='data_fabricacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Fabricação'),
        ),
        migrations.AddField(
            model_name='produto',
            name='data_validade',
            field=models.DateField(blank=True, help_text='Importante para produtos perecíveis.', null=True, verbose_name='Data de Validade'),
        ),
    ]
