# Generated by Django 5.2.3 on 2025-08-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_perfil_imagem_carrossel1_perfil_imagem_carrossel2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='objetivo',
            field=models.TextField(blank=True, help_text='Descrição dos seus objetivos e trabalhos da ONG', null=True, verbose_name='Descrição da Empresa/ONG'),
        ),
    ]
