from .avaliacao_viewset import *
from .categoria_viewset import *
from .cupom_viewset import *
from .dicas_sustentaveis_viewset import *
from .doacao_viewset import *
from .faleconosco_viewset import *
from .item_pedido_viewset import *
from .notificacao_viewset import *
from .pedido_viewset import *
from .perfil_viewset import *
from .produto_viewset import *
from .receita_viewset import *
from .usuario_viewset import *