from .receitaSerializer import *  
from .comentarioserializer import * 
from .pedidoserializers import *   
from .classeSerializer import *   
from .cupomSerializer import *   
from .classeSerializer import *  
from .itemPedidoSerializers import *
from .categoriaSerializer import *
from .vendedorSerializer import *
from .doacaoSerializer import *   
from .produtoSerializer import *   
from .PerfilSerializer import *   
from .dicas_sustentaveisSerializer import *
from .notificacaoSerializer import *
from .PerfilSerializer import *
from .usuarioSerializer import *
